name: Deploy to EC2
#makes a push to the main branch.
on:
  push:
    branches:
      - main
#Defines the jobs that are to be executed
jobs:
  deploy:
    #Runs on the latest ubuntu version
    runs-on: ubuntu-latest

    steps:
        #Step to checkout the repository
      - name: Checkout code
        #Github action to checkout the code
        uses: actions/checkout@v3

        #Setting up the SSH agent.
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

        #Deploys updated code to the EC2 instance.
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@34.193.120.111 "/home/ubuntu/deploy.sh"
